#### Get Home by ID
GET {{BudgetBeavers_API_HostAddress}}/api/home/9f50e098-2ba3-4bee-8642-42d1e94fa662
Accept: application/json

### Create A new Home
#POST {{BudgetBeavers_API_HostAddress}}/api/home
#Content-Type: application/json
#
#{
#  "name": "My First Home"
#}

### Update Home by ID
#PUT {{BudgetBeavers_API_HostAddress}}/api/home/9f50e098-2ba3-4bee-8642-42d1e94fa662
#Content-Type: application/json
#
#{
#  "name": "My Updated Home"
#}

### Delete Home by ID
#DELETE {{BudgetBeavers_API_HostAddress}}/api/home/9f50e098-2ba3-4bee-8642-42d1e94fa662
